import {
  ShoppingBag, ShoppingCart, Store, Package, Truck, Bike, MapPin, Clock, Star, Heart,
  ThumbsUp, Award, Trophy, Gift, Tag, Percent, CreditCard, Wallet, ShieldCheck, Shield,
  Lock, CheckCircle, CheckCircle2, Zap, Flame, Sparkles, TrendingUp, Users, User, Phone,
  Mail, MessageCircle, Headphones, Smartphone, Camera, Wifi, Globe, Sun, Moon, Car, Home,
  Building2, Briefcase, Gem, Crown, Bell, Calendar, RotateCcw, Recycle,
} from 'lucide-react';

export const ICON_LIBRARY = [
  { name: 'ShoppingBag', Icon: ShoppingBag },
  { name: 'ShoppingCart', Icon: ShoppingCart },
  { name: 'Store', Icon: Store },
  { name: 'Package', Icon: Package },
  { name: 'Truck', Icon: Truck },
  { name: 'Bike', Icon: Bike },
  { name: 'MapPin', Icon: MapPin },
  { name: 'Clock', Icon: Clock },
  { name: 'Star', Icon: Star },
  { name: 'Heart', Icon: Heart },
  { name: 'ThumbsUp', Icon: ThumbsUp },
  { name: 'Award', Icon: Award },
  { name: 'Trophy', Icon: Trophy },
  { name: 'Gift', Icon: Gift },
  { name: 'Tag', Icon: Tag },
  { name: 'Percent', Icon: Percent },
  { name: 'CreditCard', Icon: CreditCard },
  { name: 'Wallet', Icon: Wallet },
  { name: 'ShieldCheck', Icon: ShieldCheck },
  { name: 'Shield', Icon: Shield },
  { name: 'Lock', Icon: Lock },
  { name: 'CheckCircle', Icon: CheckCircle },
  { name: 'CheckCircle2', Icon: CheckCircle2 },
  { name: 'Zap', Icon: Zap },
  { name: 'Flame', Icon: Flame },
  { name: 'Sparkles', Icon: Sparkles },
  { name: 'TrendingUp', Icon: TrendingUp },
  { name: 'Users', Icon: Users },
  { name: 'User', Icon: User },
  { name: 'Phone', Icon: Phone },
  { name: 'Mail', Icon: Mail },
  { name: 'MessageCircle', Icon: MessageCircle },
  { name: 'Headphones', Icon: Headphones },
  { name: 'Smartphone', Icon: Smartphone },
  { name: 'Camera', Icon: Camera },
  { name: 'Wifi', Icon: Wifi },
  { name: 'Globe', Icon: Globe },
  { name: 'Sun', Icon: Sun },
  { name: 'Moon', Icon: Moon },
  { name: 'Car', Icon: Car },
  { name: 'Home', Icon: Home },
  { name: 'Building2', Icon: Building2 },
  { name: 'Briefcase', Icon: Briefcase },
  { name: 'Gem', Icon: Gem },
  { name: 'Crown', Icon: Crown },
  { name: 'Bell', Icon: Bell },
  { name: 'Calendar', Icon: Calendar },
  { name: 'RotateCcw', Icon: RotateCcw },
  { name: 'Recycle', Icon: Recycle },
];

export const ICON_MAP = ICON_LIBRARY.reduce((acc, { name, Icon }) => {
  acc[name] = Icon;
  return acc;
}, {});
